
#ifndef SYSTEM_H
#define SYSTEM_H

#define USE_CON

////////////////////REGISTER_VALUE////////////////////////////////
#define INPUT 1
#define OUTPUT 0
#define DIGITAL 0
#define ANALOG 1
////////////////////////INTERNAL_LED/////////////////////////////////
#define LED_RED1 LATE0
#define LED_RED2 LATE1
#define LED_GREEN1 LATE2
#define LED_GREEN2 LATC0
#define LED_BLUE1 LATC1
#define LED_BLUE2 LATC2
///////////////////////////EXTERNAL_OUT////////////////////////////////
#define EXT_OUT1 LATD2
#define EXT_OUT2 LATD3

#ifdef USE_CON
////////////////////////////////CONECTERS//////////////////////////////
/*CONECTER1_INITIALIZATION*/
#define SETUPCON1_A1(VAL) TRISAbits.TRISA5 = VAL
#define SETUPCON1_A2(VAL) TRISAbits.TRISA4 = VAL
#define SETUPCON1_D1(VAL) TRISAbits.TRISA3 = VAL
/*CONECTER2_INITIALIZATION*/
#define SETUPCON2_A1(VAL) TRISAbits.TRISA0 = VAL
#define SETUPCON2_A2(VAL) TRISAbits.TRISA1 = VAL
#define SETUPCON2_D1(VAL) TRISAbits.TRISA2 = VAL
/*CONECTER3_INITIALIZATION*/
#define SETUPCON3_A1(VAL) TRISBbits.TRISB5 = VAL
#define SETUPCON3_A2(VAL) TRISBbits.TRISB4 = VAL
#define SETUPCON3_D1(VAL) TRISBbits.TRISB3 = VAL
/*CONECTER4_INITIALIZATION*/
#define SETUPCON4_A1(VAL) TRISBbits.TRISB2 = VAL
#define SETUPCON4_A2(VAL) TRISBbits.TRISB1 = VAL
#define SETUPCON4_D1(VAL) TRISBbits.TRISB0 = VAL

/*CONECTER1_ANALOGINITIALIZATION*/
//PIC16F1939'S RA4 IS NOT ANALOGINPUT. 
#define ANALOGSETCON1_A2(VAL) ANSELAbits.ANSA4 = VAL
#define ANALOGSETCON1_D1(VAL) ANSELAbits.ANSA3 = VAL
/*CONECTER2_ANALOGINITIALIZATION*/
#define ANALOGSETCON2_A1(VAL) ANSELAbits.ANSA0 = VAL
#define ANALOGSETCON2_A2(VAL) ANSELAbits.ANSA1 = VAL
#define ANALOGSETCON2_D1(VAL) ANSELAbits.ANSA2 = VAL
/*CONECTER3_ANALOGINITIALIZATION*/
#define ANALOGSETCON3_A1(VAL) ANSELAbits.ANSA5 = VAL
#define ANALOGSETCON3_A2(VAL) ANSELBbits.ANSB4 = VAL
#define ANALOGSETCON3_D1(VAL) ANSELBbits.ANSB3 = VAL
/*CONECTER4_ANALOGINITIALIZATION*/
#define ANALOGSETCON4_A1(VAL) ANSELBbits.ANSB2 = VAL
#define ANALOGSETCON4_A2(VAL) ANSELBbits.ANSB1 = VAL
#define ANALOGSETCON4_D1(VAL) ANSELBbits.ANSB0 = VAL

/*CONECTER1_OUTPUT*/
#define OUTCON1_A1 LATA4
#define OUTCON1_A2 LATA5
#define OUTCON1_D1 LATA3
/*CONECTER2_OUTPUT*/
#define OUTCON2_A1 LATA0
#define OUTCON2_A2 LATA1
#define OUTCON2_D1 LATA2
/*CONECTER3_OUTPUT*/
#define OUTCON3_A1 LATB5
#define OUTCON3_A2 LATB4
#define OUTCON3_D1 LATB3
/*CONECTER4_OUTPUT*/
#define OUTCON4_A1 LATB2
#define OUTCON4_A2 LATB1
#define OUTCON4_D1 LATB0
#endif
#endif